print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("Boing from chad")
print("Boing from chad 2")
print("Hello Anna!")
print("Hello Zak!")
print("Hello Zainab!")
print("Hello again, Zainab!!!")
print("Hello again, Zainab!")
print("Hello again, Zainab!")
print("Hello Test")
