print("this is wanda")
print('this is wanda too')
print("Wanda testing v0.8.0") # local
print("Wanda testing v0.8.0 Preflight 0.1")
print("Wanda testing notifications 0.2")
print("Wanda testing notifications 0.3")
print("Wanda testing notifications 0.4")
print("Wanda testing notifications 0.41")
print("Wanda testing notifications 0.5")
print("Wanda testing notifications 0.51")
print("Wanda testing notifications 0.52")
print("Wanda testing notifications 0.53")
print("Wanda testing notifications 0.54")
print("Wanda testing notifications 0.55")
print("Wanda testing notifications 0.56")
print("Wanda testing notifications 0.57")
print("Wanda testing notifications 0.58")
print("Wanda testing notifications 0.6")
print("Wanda testing notifications 0.61")
print("Wanda testing notifications 0.62")
print("Wanda testing notifications 0.63")
print("Wanda testing notifications 0.64")
print("Wanda testing notifications 0.65")
print("Wanda testing notifications 0.66")
