

name: Deploy to Amazon ECS

on:
  push:
    branches: [ "henry-richard-patch-499" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # Runs a single command using the runners shell
    - name: Simulated compile
      run: echo Compile

      # Runs a set of commands using the runners shell
    - name: Simulated test
      run: |
        sleep 5
        echo Test complete
