name: neutral-workflow
on: [pull_request]
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - name: Failing step
      id: demo
      run: exit 1
    - name: The demo step has failed
      if: ${{ failure() && steps.demo.conclusion == 'failure' }}

