name: timeout-workflow
on: [pull_request]
jobs:
  timeout_job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: Timeout step
      run: |
        sleep 120s
        echo "Hello, world!"
