name: timeout-workflow
on: [pull_request]
jobs:
  timeout_job:
    runs-on: ubuntu-latest
    timeout-minutes: 0.5
    steps:
    - name: Timeout step
      run: |
      sleep 60
      echo "Hello, world!"
